### ISSUE TITLE
git-sh-i18n: No such file or directory

### ISSUE THREAD

**Issue by esumerfd** [frej/fast-export#74] opened 2016-09-14 12:17 UTC
Where do we get this dependency?

Found this script: https://github.com/git/git/blob/master/git-sh-i18n.sh

If this is it is there an expected deployment step or just add it to the PATH.

there appears to be a python mercurial dependency as well. I guessed  at pip install mercurial.

**Comment by frej** [comment] 2016-09-14 13:48
My guess is that this is already addressed and fixed in issue #73, but from your report I can't really tell. For the future, please have a look at  [this blog post about writing effective bug reports](https://www.viget.com/articles/tips-for-writing-better-bug-reports). Feel free to close this issue if it's a duplicate of #73.

**Comment by esumerfd** [comment] 2016-09-14 13:52
That looks like it.

**Comment by frej** [comment] 2016-09-14 15:11
Closing it...

**Closed by frej** 2016-09-14 15:11 UTC
