### ISSUE TITLE
unknown revision error

### ISSUE THREAD

**Issue by rinu** [frej/fast-export#122] opened 2018-05-09 18:56 UTC
I downloaded an old mercurial repo from Google Code today and attempted to convert it to git.
I thought the issue was with using Windows but I got the exact same result on Ubuntu.

    mercurial.error.RepoLookupError: unknown revision '\kht▒ΦV▒▒▒〳▒d▒'

Now what?

**Comment by rinu** [comment] 2018-05-09 19:43
I was hoping it's something that has happened to many people before and has a simple solution. I didn't get anything useful with googling but still.

The mercurial repo is public: https://code.google.com/archive/p/kindred/source/default/source
To reproduce:
1. Download the source code from https://code.google.com/archive/p/kindred/source/default/source
2. Unzip.
3. Use the latest master of fast-export with `git clone https://github.com/frej/fast-export.git`.
4. `git init converted`.
5. `cd converted`.
6. ~/fast-export/hg-fast-export.sh -r ~/kindred

I also used an authors file but doesn't change the output. Environment is probably not relevant, this can be reproduced on Windows 7 and Ubuntu 16.04.

**Comment by frej** [comment] 2018-05-10 18:14
That repo has unnamed heads which is a concept which cannot be
represented by git. You'll either have to merge them before converting
or you have to use 'hg-fast-export.sh -r <repo> -force' to ignore them.

With Mercurial 4.5.3 and fast-export
19aa906308568c3170a8742e039a5543a673fc4f it works fine for me (using
-force). The crash you see, does it happen in a newly created git repo
or are you restaring a previously crashed conversion (you mentioned an
author's file)? Has the source repo become corrupted, i.e. do you get
any error messages if you run 'hg log -p'?

**Comment by mirner** [comment] 2018-05-11 00:51
Tried it with 2 different mercurial repositories and got the same error


```
Traceback (most recent call last):
  File "../fast-export/hg-fast-export.py", line 529, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "../fast-export/hg-fast-export.py", line 405, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "../fast-export/hg-fast-export.py", line 374, in verify_heads
    (_,_,_,_,_,_,branch,_)=get_changeset(ui,repo,h)
  File "../fast-export/hg2git.py", line 72, in get_changeset
    node=repo.lookup(revision)
  File "/Library/Python/2.7/site-packages/mercurial/localrepo.py", line 1067, in lookup
    return scmutil.revsymbol(self, key).node()
  File "/Library/Python/2.7/site-packages/mercurial/scmutil.py", line 518, in revsymbol
    raise error.RepoLookupError(_("unknown revision '%s'") % symbol)
??'curial.error.RepoLookupError: unknown revision 'Nl???:S:n$??
/usr/local/Cellar/git/2.15.0/libexec/git-core/git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2282 KiB
       pools:          2048 KiB
     objects:           234 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
```

**Comment by rinu** [comment] 2018-05-11 08:39
`hg log -p` will display the entire contents of every file.
New day, entirely new error:
```
Traceback (most recent call last):
  File "/home/rauno/fast-export/hg-fast-export.py", line 7, in <module>
    from hg2git import setup_repo,fixup_user,get_branch,get_changeset
  File "/home/rauno/fast-export/hg2git.py", line 6, in <module>
    from mercurial import hg,util,ui,templatefilters
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/hg.py", line 22, in <module>
    from . import (
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/bundlerepo.py", line 23, in <module>
    from . import (
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/cmdutil.py", line 23, in <module>
    from . import (
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/crecord.py", line 33, in <module>
    locale.setlocale(locale.LC_ALL, u'')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

I think if I had known about `-force` before I wouldn't even be here. This convert is way too difficult. I started a clean git repo yesterday. Commit history is not worth it.

**Comment by frej** [comment] 2018-05-11 08:45
@mirner: What version of Mercurial are you using? From the `/Library/Python/2.7/site-packages/mercurial/scmutil.py` path it looks like you are on OSX. Previously users have had problems with multiple versions of Mercurial and Python installed in different locations, i.e. a homebrew-installed Mercurial clashing with a different version of Mercurial and/or Python installed as a normal application. Can the Mercurial installed in `/Library/Python/2.7/site-packages/mercurial/` do a successful  `hg log -p` of your repo?

What happens if you (@rinu you can test this too) in the terminal with your installed Python 2.7  do:

```
from mercurial import hg,ui
myui=ui.ui()
myui.setconfig('ui', 'interactive', 'off')
repo=hg.repository(myui,'<path-to-hg-repo>')
[repo.changelog.rev(h) for h in repo.heads()]
```
You should get a list of version numbers. If that works, what happens if you do?
```
[repo.changelog.read(repo.lookup(h)) for h in repo.heads()]
```

**Comment by rinu** [comment] 2018-05-11 09:02
After I fixed my locales
```
>>> [repo.changelog.rev(h) for h in repo.heads()]
[147, 31]
>>> [repo.changelog.read(repo.lookup(h)) for h in repo.heads()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/localrepo.py", line 1067, in lookup
    return scmutil.revsymbol(self, key).node()
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/scmutil.py", line 518, in revsymbol
    raise error.RepoLookupError(_("unknown revision '%s'") % symbol)
mercurial.error.RepoLookupError: unknown revision '\kht�ΦV����〳�d��'
```

Even with `-force` (or `--force`) the script fails with the same error.

**Comment by frej** [comment] 2018-05-11 09:13
As the low-level Mercurial stuff fails, it's your Mercurial or Mercurial-installation that is broken. As long as the 100% Mercurial test above doesn't work, fast-export can't really be blamed for for failing, sorry!

**Comment by frej** [comment] 2018-05-11 10:39
I had a brain wave and checked if there is a new Mercurial release, last saturday 4.6 was released and with it I can reproduce the problem.

**Comment by frej** [comment] 2018-05-11 11:18
If you are running Mercurial 4.6, try the hg-4.6-compat branch and let me know if it works

**Comment by rinu** [comment] 2018-05-11 11:33
`hg-4.6-compat` branch:
```
~/fast-export/hg-fast-export.sh -r ~/kindred -A ~/authors --force
Loaded 7 authors
Error: repository has at least one unnamed head: hg r31
master: Exporting full revision 1/148 with 1/0/0 added/changed/removed files
master: Exporting simple delta revision 2/148 with 2/0/0 added/changed/removed files
master: Exporting simple delta revision 3/148 with 0/1/0 added/changed/removed files
master: Exporting simple delta revision 4/148 with 0/0/1 added/changed/removed files
master: Exporting simple delta revision 5/148 with 2/0/0 added/changed/removed files
master: Exporting simple delta revision 6/148 with 0/2/0 added/changed/removed files
master: Exporting simple delta revision 7/148 with 4/0/0 added/changed/removed files
master: Exporting simple delta revision 8/148 with 0/5/0 added/changed/removed files
master: Exporting simple delta revision 9/148 with 0/2/0 added/changed/removed files
master: Exporting simple delta revision 10/148 with 1/0/0 added/changed/removed files
master: Exporting simple delta revision 11/148 with 0/0/1 added/changed/removed files
master: Exporting simple delta revision 12/148 with 0/0/1 added/changed/removed files
master: Exporting simple delta revision 13/148 with 12/1/0 added/changed/removed files
Traceback (most recent call last):
  File "/home/rauno/fast-export/hg-fast-export.py", line 530, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/home/rauno/fast-export/hg-fast-export.py", line 428, in hg2git
    sob,brmap,hgtags,encoding,fn_encoding)
  File "/home/rauno/fast-export/hg-fast-export.py", line 237, in export_commit
    added,changed,removed=get_filechanges(repo,revision,parents,man)
  File "/home/rauno/fast-export/hg-fast-export.py", line 82, in get_filechanges
    mright=repo.changectx(p).manifest()
  File "/home/rauno/.local/lib/python2.7/site-packages/mercurial/repoview.py", line 255, in __getattr__
    return getattr(self._unfilteredrepo, attr)
AttributeError: 'localrepository' object has no attribute 'changectx'
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:           78 (         3 duplicates                  )
      blobs  :           31 (         2 duplicates         13 deltas of         30 attempts)
      trees  :           33 (         1 duplicates         18 deltas of         33 attempts)
      commits:           14 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           1 (         1 loads     )
      marks:           1024 (        14 unique    )
      atoms:             21
Memory total:          2344 KiB
       pools:          2110 KiB
     objects:           234 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 8589934592
pack_report: pack_used_ctr            =         13
pack_report: pack_mmap_calls          =          6
pack_report: pack_open_windows        =          1 /          1
pack_report: pack_mapped              =      25014 /      25014
---------------------------------------------------------------------
```

It did a lot more than before. There was an error but it looks like git repo now. It doesn't have all the commits though, the later ones are missing.

**Comment by rinu** [comment] 2018-05-11 11:44
I'm not sure actually how I got the latest Mercurial version. It must have been installed by `pip install mercurial`. Usually Ubuntu LTS has the version of each package that was out when that version of Ubuntu itself was released, in this case 2 years ago.

**Comment by rinu** [comment] 2018-05-11 13:26
It works now, meaning it doesn't crash and creates a git repo with all of the commits.
Is it normal that in the resulting git repo all files are deleted and staged? After a `git reset --hard` it's perfect.

**Comment by frej** [comment] 2018-05-11 13:41
> It works now, meaning it doesn't crash and creates a git repo with all
> of the commits.

Nice!

> Is it normal that in the resulting git repo all files are deleted and
> staged? After a git reset --hard it's perfect.

That's expected, fast-export can't know for sure which of multiple
branches the user wants to have checked out, so instead of having
heuristics it just leaves it to the user. That way it also works nicely
if your git repo is bare.

**Comment by rinu** [comment] 2018-05-11 13:45
Thanks for all the help. I think the issue can be closed now.

**Comment by frej** [comment] 2018-05-11 13:47
I'll keep it open for @mirner to test it too, then I'll clean it up and push it to master.

**Comment by vaizki** [comment] 2018-05-23 08:18
I also had these issues with mercurial 4.6 but the hg-4.6-compat branch worked fine, thank you!

**Comment by pxgamer** [comment] 2018-05-23 16:29
Seems to be working fine with the new branch. 👍

**Comment by tsdh** [comment] 2018-05-24 05:31
I've had the same problem, and it seems the conversion now works with the hg-4.6-compat branch.  Thanks a lot!

**Comment by frej** [comment] 2018-06-10 14:11
I'll close this as the Mercurial 4.6 fixes are now in a release version.

**Closed by frej** 2018-06-10 14:11 UTC
Labels: patch-exists, user-support
