### ISSUE TITLE
`--force` option is not accepted

### ISSUE THREAD

**Issue by alexreg** [frej/fast-export#190] opened 2020-01-27 01:29 UTC
If I specify it as the first option, I get:

```
no repo given, use -r flag
```

If I specify it as any subsequent option (including the last), I get:

```
Error: The option core.ignoreCase is set to true in the git
repository. This will produce empty changesets for renames that just
change the case of the file name.
Use --force to skip this check or change the option with
git config core.ignoreCase false
```

**Comment by frej** [comment] 2020-01-28 20:48
Duplicate of #57, feel free to submit a patch.

**Closed** 2020-01-29 18:22 UTC
Labels: contribution-required, patches-welcome, verified-bug
