### ISSUE TITLE
Getting error: "hg-fast-exports requires a readlink implementation which knows  how to canonicalize paths in order to be called via a symlink"

### ISSUE THREAD

**Issue by nanocyto** [frej/fast-export#161] opened 2019-08-27 22:11 UTC
After learning about a major vendor dropping Mercurial support, I came looking for a way to convert my large repository to git. I'm getting the following error using git bash in Win10.

`hg-fast-exports requires a readlink implementation which knows  how to canonicalize paths in order to be called via a symlink.`

I'm guessing this is some limitation of Windows. I don't think I have symlinks in my hg repo so I don't entirely understand why I'd need a readlink implementation

I'm using GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Comment by frej** [comment] 2019-08-30 14:14
The shell script needs to locate the `hg-fast-export.py` file in order to do its job. It does that by running `readlink -f $0` (or `greadlink` if it is available) . If that fails, it will look for it in `$(dirname "$(which "$0")")`, if that fails you'll get the error message you have observed. This is done in the first 20 lines of `hg-fast-export.sh`.

You could try to run `readlink` and `dirname` by hand to debug this, and/or add printouts to the logic in  `hg-fast-export.sh` to figure out what happens.

**Comment by nanocyto** [comment] 2019-08-30 21:54
Got it! I was running the script from the folder it was downloaded into and assumed the .sh would look in its own folder for the .py but I guess it doesn't. To work around the issue I created a folder `C:\Users\{username}\bin` and dumped the contents of `fast-export-master` in there. Everything worked fine from there.

**Comment by frej** [comment] 2019-08-31 10:03
> Got it! I was running the script from the folder it was downloaded into and assumed the .sh would look in its own folder for the .py but I guess it doesn't. 

It does, that's what the `readlink` and `dirname` logic is for. It's a bit complicated as we want to support both having `hg-fast-export.sh` in the path, as a symlink from a directory in the path and invoked by an  absolute or relative path. I strongly suspect you are missing `readlink` and/or `dirname`.

But as you have got it working, I'll close this issue.

**Closed by frej** 2019-08-31 10:03 UTC
Labels: not-available-to-maintainer, user-support, wintendo

**Comment by nanocyto** [comment] 2019-09-03 17:16
Just for documentation sake, GitBash does have `dirname `and `readlink` 

```
User@UserPC01 MINGW64 ~
$ dirname --version
dirname (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie and Jim Meyering.

User@UserPC01 MINGW64 ~
$ readlink --version
readlink (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Dmitry V. Levin.
```

**Comment by alexey-sh** [comment] 2019-10-01 18:27
I received the following on my mac
```
$ dirname --version
dirname: illegal option -- -
usage: dirname path
$ readlink --version
readlink: illegal option -- -
usage: readlink [-n] [file ...]
```

**Comment by rayluo** [comment] 2021-01-05 07:29
Sharing a known issue and workaround:

I hit the same issue "hg-fast-exports requires a readlink implementation which knows how to canonicalize paths in order to be called via a symlink". And the reason was that my `fast-export` clone was on an FAT32 partition, which does not have `+x` execution permission. Once I move the entire `fast-export` folder into an `ext4` partition and then `chmod +x path/to/the/hg-fast-export.sh`, it worked. Given that @nanocyto was using Git Bash on Windows, and [his/her workaround](https://github.com/frej/fast-export/issues/161#issuecomment-526761567) was also about the execution permission, I guess that was the same root cause.
