### ISSUE TITLE
mercurial.error.RepoLookupError: unknown revision 'y�%fI�dB���rD�R�?t'

### ISSUE THREAD

**Issue by gcb** [frej/fast-export#125] opened 2018-05-27 18:51 UTC
Not even sure where to start debugging this one

Python 2.7.12 on Ubuntu 16.04.4 LTS

fast-export commit 19aa906308568c3170a8742e039a5543a673fc4f (HEAD -> master, tag: v180317)

want to migrate personal(hg repo) -> personalgit
```bash
$ mkdir personalgit
$ cd personalgit
$ git init
$ tree -L 1 ../
../
├── fast-export
├── personal
└── personalgit
$ ../fast-export/hg-fast-export.sh  -r ../personal/
Traceback (most recent call last):
  File "/media/sf_code_ssd/fast-export/hg-fast-export.py", line 529, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/media/sf_code_ssd/fast-export/hg-fast-export.py", line 405, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "/media/sf_code_ssd/fast-export/hg-fast-export.py", line 374, in verify_heads
    (_,_,_,_,_,_,branch,_)=get_changeset(ui,repo,h)
  File "/media/sf_code_ssd/fast-export/hg2git.py", line 72, in get_changeset
    node=repo.lookup(revision)
  File "/home/user/.local/lib/python2.7/site-packages/mercurial/localrepo.py", line 1067, in lookup
    return scmutil.revsymbol(self, key).node()
  File "/home/user/.local/lib/python2.7/site-packages/mercurial/scmutil.py", line 518, in revsymbol
    raise error.RepoLookupError(_("unknown revision '%s'") % symbol)
mercurial.error.RepoLookupError: unknown revision 'y�%fI�dB���rD�R�?t'
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2282 KiB
       pools:          2048 KiB
     objects:           234 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 8589934592
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
```

The term revision can mean two things in hg: https://www.mercurial-scm.org/wiki/Revision

I did not find anything non-ascii on hg log

**Comment by frej** [comment] 2018-05-28 16:20
Are you using Mercurial 4.6? If so, this is probably a duplicate of #122
and for that there is a fix in the hg-4.6-compat branch

**Comment by frej** [comment] 2018-06-10 14:08
@gcb: From your other activity, it appears that this is resolved, I'll close this issue.

**Closed by frej** 2018-06-10 14:08 UTC

**Comment by gcb** [comment] 2018-06-13 02:17
i honestly do not recall now if i worked around this or used something else, but i'm not impacted anymore :) thanks

**Comment by caot** [comment] 2018-12-13 20:46
Mercurial 4.5 worked for me.
