### ISSUE TITLE
ImportError: cannot import name revsymbol

### ISSUE THREAD

**Issue by camuso** [frej/fast-export#134] opened 2018-07-16 13:59 UTC
$ hg-fast-export.sh -r ../hg
Traceback (most recent call last):
  File "/home/tcamuso/bin/hg-fast-export.py", line 7, in <module>
    from mercurial.scmutil import revsymbol
ImportError: cannot import name revsymbol

Please help

**Comment by frej** [comment] 2018-07-16 14:38
Duplicate of #132

**Closed by frej** 2018-07-16 14:38 UTC

**Comment by camuso** [comment] 2018-07-16 17:22
OK, I downgraded to version v180317 as instructed in #132, and the problem is gone.
This bug needs to be fixed.
