### ISSUE TITLE
Got error at execution "unnamed head"

### ISSUE THREAD

**Issue by mathben** [frej/fast-export#101] opened 2017-07-27 16:19 UTC
I test with this mercurial repo
https://bitbucket.org/eigen/eigen

```
hg clone https://bitbucket.org/eigen/eigen
git clone https://github.com/frej/fast-export.git
mkdir eigen_git
cd eigen_git
git init
~/fast-export/hg-fast-export.sh -r ../eigen
git checkout HEAD
```
And receive when I call hg-fast-export.sh

> Error: repository has at least one unnamed head: hg r8867

**Comment by frej** [comment] 2017-07-29 14:16
Searching the closed tickets for the phrase "unnamed head" turns up #9 which explains what the problem is and also gives a workaround. If you only want to convert the default branch, #49 gives you the hint to run with `-b default`. #85 mentions using `--force` to ignore unnamed heads. #86 describes how you can use `hg strip` to remove them on the hg side.

Will close this one, feel free to reopen if your problem is not handled by one of these solutions.

**Closed by frej** 2017-07-29 14:16 UTC
