### ISSUE TITLE
Asks for --marks option when starting conversion of simple repo for the first time

### ISSUE THREAD

**Issue by TuggyNE** [frej/fast-export#256] opened 2021-02-12 21:13 UTC
I'm trying to convert a pretty simple repository (a few dozen revisions, a few dozen files) using Python 3.7 on Windows from Git Bash. Very simple command-line, too, run from inside a completely fresh git repo:
`python ../path/to/hg-fast-export.py -r ../path/to/hg-repo`
It tells me I didn't pass a `--marks` parameter. Well, no, of course not, I have no reason to have whatever a marksfile is and no obvious way to get one. Adding `--force` does nothing.

Running the shell script instead gives a different error:
```
C:/Users/Nathan/Programs/Scripts/External/hg-fast-export/hg-fast-export.py:269: FutureWarning: Possible nested set at position 2
  p=re.compile(b'([[ ~^:?\\\\*]|\.\.)')
Traceback (most recent call last):
  File "C:/Users/Nathan/Programs/Scripts/External/hg-fast-export/hg-fast-export.py", line 730, in <module>
    plugins=plugins_dict))
  File "C:/Users/Nathan/Programs/Scripts/External/hg-fast-export/hg-fast-export.py", line 542, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,ignore_unnamed_heads,branchesmap):
  File "C:/Users/Nathan/Programs/Scripts/External/hg-fast-export/hg-fast-export.py", line 494, in verify_heads
    sha1=get_git_sha1(sanitized_name)
  File "C:\Users\Nathan\Programs\Scripts\External\hg-fast-export\hg2git.py", line 136, in get_git_sha1
    "--quiet", ref.encode('utf8')])
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

**Comment by frej** [comment] 2021-02-14 14:01
The shell-script is the user-facing entry point to fast-export.

You don't say which version of Mercurial you are use nor the full Python version, but as is is 3.7.x I suspect that the error you see is a duplicate of #252.

**Comment by frej** [comment] 2021-07-27 13:08
No activity in more than 90 days, closing.

**Closed by frej** 2021-07-27 13:08 UTC
Labels: need-more-info, user-support, wintendo
