### ISSUE TITLE
fails on https://bitbucket.org/pypy/pypy with Broken pipe

### ISSUE THREAD

**Issue by scottidler** [frej/fast-export#52] opened 2015-09-07 03:20 UTC
Fails on normal run:

    ><(((º> ~/repos/fast-export/hg-fast-export.sh -r ~/repos/pypy         
    Error: repository has at least one unnamed head: hg r72634

Fails with --force:

    ><(((º> ~/repos/fast-export/hg-fast-export.sh -r ~/repos/pypy/ --force
    Traceback (most recent call last):
      File "/home/saidler/repos/fast-export/hg-fast-export.py", line 468, in <module>
      notes=options.notes,encoding=encoding))
      File "/home/saidler/repos/fast-export/hg-fast-export.py", line 377, in hg2git
      sob,brmap,hgtags,notes,encoding)
      File "/home/saidler/repos/fast-export/hg-fast-export.py", line 235, in export_commit
      export_file_contents(ctx,man,changed,hgtags,encoding)
      File "/home/saidler/repos/fast-export/hg-fast-export.py", line 141, in export_file_contents
      wr(d)
     File "/home/saidler/repos/fast-export/hg-fast-export.py", line 37, in wr
     wr_no_nl(msg)
     File "/home/saidler/repos/fast-export/hg-fast-export.py", line 34, in wr_no_nl
     sys.stdout.write(msg)
     IOError: [Errno 32] Broken pipe

**Comment by frej** [comment] 2015-09-07 08:44
Use --force. This error message (on this particular repo too) and what you have
to do to is covered in issue #49.

**Comment by frej** [comment] 2015-09-07 08:45
Duplicate of issue #49, closing

**Closed by frej** 2015-09-07 08:45 UTC
