### ISSUE TITLE
yet another issue on unnamed heads

### ISSUE THREAD

**Issue by dedabob** [frej/fast-export#220] opened 2020-04-19 22:41 UTC
We started migrating our mercurial repositories to git ones and we got stuck into the problem of _unnamed heads_. This problem has been discussed in closed issue #9 but i think it's related to open issue #61. Basically we have been using mercurial bookmarks as git branches.
To migrate those repositories we are emulating forks to have a git branch for each mercurial head.
The process is based on getting the common ancestors of the heads (using mercurial APIs), clone and fork them, The forks are then added as remote repositories just to get their branches and removed afterwards. It does not uses the *force* option and does not require extra commits, which avoids closed mercurial branches to pop up.

Down below are the commands executed to successfully export a repository with revisions 849 and 879 as heads and revision 827 as common ancestor. I guess they can be simplified and automated. 

**Note**: We brutally copied the folders as a work-around to issue #114.

```
# clone up to common ancestor
hg clone hg-repo hg-repo-ancestor -r 827
# export to git
git init git-repo-ancestor
cd git-repo-ancestor
../fast-export/hg-fast-export.sh -r ../hg-repo-ancestor
cd ..
# copy common ancestors to 2 new repository
cp -a hg-repo-ancestor hg-repo-v15.x
cp -a hg-repo-ancestor hg-repo-master
cp -a git-repo-ancestor git-repo-v15.x
cp -a git-repo-ancestor git-repo
# for each copied ancestor pull one head and export to git
hg -R hg-repo-v15.x pull -r 849 -u
cd git-repo-v15.x
../fast-export/hg-fast-export.sh -r ../hg-repo-v15.x
cd ..
hg -R hg-repo-master pull -r 879 -u
cd git-repo
../fast-export/hg-fast-export.sh -r ../hg-repo-master
# add the other repositority as a remote
git remote add v15.x ../git-repo-v15.x
# fetch from the other repository
git fetch v15.x master
# create branch
git branch v15.x v15.x/master
# remove the other repository
git remote remove v15.x
# checkout master branch
git checkout HEAD
# clean up
cd ..
rm -fr hg-repo-ancestor hg-repo-v15.x hg-repo-master \
        git-repo-ancestor git-repo-v15.x
```

**Comment by frej** [comment] 2020-04-30 13:23
Are you aware if @chrisjbillington's  [hg-export-tool](https://github.com/chrisjbillington/hg-export-tool)? I think it will give you a git branch for each Mercurial head .

**Comment by sschaap** [comment] 2020-04-30 21:25
We have a similar issue on a third-party repo that has loads of unnamed heads, mostly due to closed/reused branches. Was considering whether to add a `--tag-heads` switch to create `heads/{branch}/{hash}` tags for each hg head and disables the unnamed heads check.

Thoughts?

**Comment by dedabob** [comment] 2020-05-04 10:11
> 
> 
> Are you aware if @chrisjbillington's [hg-export-tool](https://github.com/chrisjbillington/hg-export-tool) (it is mentioned in the Notes/Limitations section of the readme)? I think it will give you a git branch for each Mercurial head .

[Pro Git book](https://git-scm.com/book/it/v2/Git-and-Other-Systems-Migrating-to-Git) pointed me to this tool, so I didn't look for alternatives.

I gave @chrisjbillington's tool a try. It amends  head commits, which means it _strips_ those commits and creates new ones, so it's fine if changing the history is not a problem.

I'm going to try [hg-git](https://foss.heptapod.net/mercurial/hg-git). It seems to ignore branches and just export mercurial bookmarks to git branches without changing the history, which is the feature of issue #61. @sschaap, check if it's suitable for your requirements.

**Comment by frej** [comment] 2020-05-06 13:53
As this basically seems to be a duplicate of the feature request in #61, I'll close this issue.

**Closed by frej** 2020-05-06 13:53 UTC
Labels: user-support
