### ISSUE TITLE
Feature Request: Read and store hg-subversion markers during conversions

### ISSUE THREAD

**Issue by SirIntellegence** [frej/fast-export#257] opened 2021-02-14 18:24 UTC
My company has a repository that was a simple svn repo for which I made a mercurial mirror (using hg-subversion) at some point in time. I am now thinking of using git so I can use https://github.com/bozaro/git-as-svn for reasons. The mercurial mirror has markers in it for what the original svn revision number is when it was converted. I would really like it if that could be imported into the metadata around where one of the plugins copies the hg hash if possible.

**Comment by frej** [comment] 2021-02-15 15:40
I'm not really sure what you are asking for. Are you asking about a new feature adapted to the output of your (unspecified) SVN to Mercurial conversion? Or are you asking for the addition of additional information (again unspecified) to be exposed in the plugin API? If it is the latter, please tell me what information that is lacking, or even better, send a patch.

Custom mangling of commit messages is something the plugin system was designed to do. Unless the tool you have used for the initial conversion from SVN and git-as-svn are widely used, I'd say that such a feature is of too niche to be maintained together with fast-export.

**Comment by SirIntellegence** [comment] 2021-02-15 16:51
I mostly mean the svn revision markers created by https://www.mercurial-scm.org/wiki/HgSubversion. The extension itself seems to be sorely outdated and unmaintained (see https://stackoverflow.com/a/64563930/1366594), so I understand if you don't want to implement that. What would be nice is to be able to grab a list of unclaimed properties (or something like that) for each revision so I don't have to figure out how to invoke mercurial to get the property for that revision.

**Comment by frej** [comment] 2021-02-15 19:34
After some quick Googling it looks like Mercurial does not natively support the kind of properties you are talking about. I very much suspect that the properties you are talking about comes from the HgSubversion extension you mentioned, but I could be wrong. Feel free to submit a patch if there are such generic properties (not depending on a particular extension).

If you don't want to spawn a hg command for each revision and the properties depend on an extension, you could traverse the complete history in Mercurial, dump a list of `<hash>:<property>` and then feed that to your plugin.

**Comment by SirIntellegence** [comment] 2021-02-18 20:37
Ok. I did some research and found this in case it helps: https://stackoverflow.com/q/4268745/1366594

**Comment by frej** [comment] 2021-02-19 14:58
Feel free to submit a patch that exposes the `extra`-field to plugins.

**Comment by frej** [comment] 2021-02-26 15:48
Fix merged in #260

**Closed by frej** 2021-02-26 15:48 UTC
Labels: contribution-required, feature-request
