### ISSUE TITLE
gets confused by missing original branch commits in a clone

### ISSUE THREAD

**Issue by imz** [frej/fast-export#79] opened 2016-09-22 18:31 UTC
I had a local clone of the orginal hg repo, which I initially used for
`hg-fast-export -r ../orig_hg -M master`

Then I committed my change(s) in a another local hg clone of the
original clone (a separate hg repo for my changes is a way to easily
separate them in the resulting git branches).

I imported my changes with `hg-fast-export -r ../my_hg -M my`

I was very surprized not to see my new change on top of the `master`
git branch, as a single new commit of the `my` git branch. (This is
what I can reproduce reliably; once there was also a strange case,
when `my` and `master` git branches diverged, although `master` should
be the ancestor. I think it was a more complex case of the same
problem.)

### in a "top-level" dir

    mkdir orig_hg
    cd orig_hg/

### in orig_hg/

    hg init
    echo a >f
    hg add f
    hg commit -m A
    hg branch t
    echo b >f
    hg commit -m B
    hg update default
    echo c >f
    hg commit -m C
    cd ..

### in the top-level dir

    hg clone -b default orig_hg my_hg
    cd my_hg/

### in my_hg/

    echo d >f
    hg commit -m D
    cd ..

### in the top-level dir

    mkdir tmp_git
    cd tmp_git/

### in tmp_git/

    tmp_git $ git init
    tmp_git $ hg-fast-export -r ../orig_hg -M master
    master: Exporting full revision 1/3 with 1/0/0 added/changed/removed files
    t: Exporting simple delta revision 2/3 with 0/1/0 added/changed/removed files
    master: Exporting simple delta revision 3/3 with 0/1/0 added/changed/removed files
    Issued 3 commands
    git-fast-import statistics:
    ---------------------------------------------------------------------
    Alloc'd objects:       5000
    Total objects:            9 (         0 duplicates                  )
          blobs  :            3 (         0 duplicates          0 deltas of          0 attempts)
          trees  :            3 (         0 duplicates          0 deltas of          3 attempts)
          commits:            3 (         0 duplicates          0 deltas of          0 attempts)
          tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
    Total branches:           2 (         2 loads     )
          marks:           1024 (         3 unique    )
          atoms:              1
    Memory total:          2344 KiB
           pools:          2110 KiB
         objects:           234 KiB
    ---------------------------------------------------------------------
    pack_report: getpagesize()            =       4096
    pack_report: core.packedGitWindowSize = 1073741824
    pack_report: core.packedGitLimit      = 8589934592
    pack_report: pack_used_ctr            =          6
    pack_report: pack_mmap_calls          =          2
    pack_report: pack_open_windows        =          1 /          1
    pack_report: pack_mapped              =        614 /        614
    ---------------------------------------------------------------------
    
    tmp_git $ gitk --all
    tmp_git $ hg-fast-export -r ../my_hg -M my
    Issued 0 commands
    git-fast-import statistics:
    ---------------------------------------------------------------------
    Alloc'd objects:       5000
    Total objects:            0 (         0 duplicates                  )
          blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
          trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
          commits:            0 (         0 duplicates          0 deltas of          0 attempts)
          tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
    Total branches:           0 (         0 loads     )
          marks:           1024 (         0 unique    )
          atoms:              0
    Memory total:          2282 KiB
           pools:          2048 KiB
         objects:           234 KiB
    ---------------------------------------------------------------------
    pack_report: getpagesize()            =       4096
    pack_report: core.packedGitWindowSize = 1073741824
    pack_report: core.packedGitLimit      = 8589934592
    pack_report: pack_used_ctr            =          0
    pack_report: pack_mmap_calls          =          0
    pack_report: pack_open_windows        =          0 /          0
    pack_report: pack_mapped              =          0 /          0
    ---------------------------------------------------------------------
    
    tmp_git $ hg-fast-export -r ../my_hg -M my
    Issued 0 commands
    git-fast-import statistics:
    ---------------------------------------------------------------------
    Alloc'd objects:       5000
    Total objects:            0 (         0 duplicates                  )
          blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
          trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
          commits:            0 (         0 duplicates          0 deltas of          0 attempts)
          tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
    Total branches:           0 (         0 loads     )
          marks:           1024 (         0 unique    )
          atoms:              0
    Memory total:          2282 KiB
           pools:          2048 KiB
         objects:           234 KiB
    ---------------------------------------------------------------------
    pack_report: getpagesize()            =       4096
    pack_report: core.packedGitWindowSize = 1073741824
    pack_report: core.packedGitLimit      = 8589934592
    pack_report: pack_used_ctr            =          0
    pack_report: pack_mmap_calls          =          0
    pack_report: pack_open_windows        =          0 /          0
    pack_report: pack_mapped              =          0 /          0
    ---------------------------------------------------------------------
    
    tmp_git $ gitk --all

No ne commit in `my`. Bad.

### A workaround:

    tmp_git $ rm -rfv .git/hg*
    rm: removing file `.git/hg2git-heads'
    rm: removing file `.git/hg2git-mapping'
    rm: removing file `.git/hg2git-marks'
    rm: removing file `.git/hg2git-state'
    tmp_git $ hg-fast-export -r ../my_hg -M my
    my: Exporting full revision 1/3 with 1/0/0 added/changed/removed files
    my: Exporting simple delta revision 2/3 with 0/1/0 added/changed/removed files
    my: Exporting simple delta revision 3/3 with 0/1/0 added/changed/removed files
    Issued 3 commands
    git-fast-import statistics:
    ---------------------------------------------------------------------
    Alloc'd objects:       5000
    Total objects:            3 (         6 duplicates                  )
          blobs  :            1 (         2 duplicates          0 deltas of          0 attempts)
          trees  :            1 (         2 duplicates          0 deltas of          1 attempts)
          commits:            1 (         2 duplicates          0 deltas of          0 attempts)
          tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
    Total branches:           1 (         1 loads     )
          marks:           1024 (         3 unique    )
          atoms:              1
    Memory total:          2344 KiB
           pools:          2110 KiB
         objects:           234 KiB
    ---------------------------------------------------------------------
    pack_report: getpagesize()            =       4096
    pack_report: core.packedGitWindowSize = 1073741824
    pack_report: core.packedGitLimit      = 8589934592
    pack_report: pack_used_ctr            =          2
    pack_report: pack_mmap_calls          =          1
    pack_report: pack_open_windows        =          1 /          1
    pack_report: pack_mapped              =        238 /        238
    ---------------------------------------------------------------------
    
    tmp_git $ gitk --all

## The cause

The cause is probably that `orig_hg` had an extra commit in branch
`t`, totalling 3 with the last sequential number 2. And in `my_hg`
with the extra branch omitted there are total 3 commits with the last
one having number 2, too.

So, it is somehow unnoticed in the result of `hg-fast-export`.

**Comment by frej** [comment] 2016-09-30 17:23
Thank you for the excellent error report, I'll start referring to it when I get vague reports!

The problem here is that fast-export never was designed to work against more than a single repo. `-r` is actually only intended to be used on the initial run (or if the repo is moved). As you noticed switching between repos this will confuse fast-export. To solve your problem I would do one of the following:

* Convert the hg repos to git on their own, then pull the two repos into a third git repo.

* Pull the two separate repos into a single hg-repo (as named branches) and then convert it wholesale into git.

**Comment by imz** [comment] 2016-09-30 18:05
On Sep 30, 2016 8:23 PM, "frej" <notifications@github.com> wrote:
>
> Thank you for the excellent error report, I'll start referring to it when
I get vague reports!

:)

> The problem here is that fast-export never was designed to work against
more than a single repo. -r is actually only intended to be used on the
initial run (or if the repo is moved). As you noticed switching between
repos this will confuse fast-export. To solve your problem I would do one
of the following:

I see. Of course, working against multiple clones would be convenient.

> Convert the hg repos to git on their own, then pull the two repos into a
third git repo.

I like this way of the available solutions.

**Comment by frej** [comment] 2016-09-30 18:35
Close the issue if that works for you, as adding support for multiple repos probably will be hairy :)

**Closed** 2016-09-30 18:36 UTC
