### ISSUE TITLE
fast-export fails if python3 is sytem-wide default

### ISSUE THREAD

**Issue by houseofsuns** [frej/fast-export#11] opened 2013-06-04 08:49 UTC
If the system default python is python3 (i.e. the symlink is /usr/bin/python -> /usr/bin/python3) then fast-export fails as it is python2 only. The error is in this case rather confusingly

<pre>
veelai@zaphod ~/fast-export $ python3 hg-fast-export.py 
Traceback (most recent call last):
  File "fast-export/hg-fast-export.py", line 6, in <module>
    from mercurial import node
ImportError: No module named mercurial
</pre>

A possible solution is to replace PYTHON=${PYTHON:-python} by PYTHON=${PYTHON:-python2} in the shell scripts and '#!/usr/bin/env python' by  '#!/usr/bin/env python2' in the python scripts. This should work in most environments, with one caveat: Debian as greatest distribution under the sky decided to be extravagant and does not ship a python2 symlink, but only python2.6 and similar.

**Comment by frej** [comment] 2016-09-30 16:51
Is this still a problem?

**Comment by bigbn** [comment] 2016-10-02 12:39
Still. Python3 can't use package mercurial, because it is not ported from python 2.

**Comment by frej** [comment] 2016-10-02 14:37
Ok. I'll leave it open then...

**Comment by mathben** [comment] 2017-07-27 16:01
It's supported now!

> \> pip3 show mercurial
> Name: mercurial
> Version: 4.2.2
> Summary: Fast scalable distributed SCM (revision control, version control) system
> Home-page: https://mercurial-scm.org/
> Author: Matt Mackall and many others
> Author-email: mercurial@mercurial-scm.org
> License: GNU GPLv2 or any later version
> Location: /usr/lib/python3.6/site-packages
> Requires:

But I got this error in execution : 
> \> ../fast-export/hg-fast-export.sh -r ../eigen
> Traceback (most recent call last):
>   File "~/fast-export/hg2git.py", line 31, in setup_repo
>     myui=ui.ui(interactive=False)
> TypeError: __init__() got an unexpected keyword argument 'interactive'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "~/fast-export/hg-fast-export.py", line 505, in <module>
>     notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
>   File "~/fast-export/hg-fast-export.py", line 381, in hg2git
>     ui,repo=setup_repo(repourl)
>   File "~/fast-export/hg2git.py", line 34, in setup_repo
>     myui.setconfig('ui', 'interactive', 'off')
>   File "/usr/lib/python3.6/site-packages/mercurial/ui.py", line 388, in setconfig
>     cfg.set(section, name, value, source)
>   File "/usr/lib/python3.6/site-packages/mercurial/config.py", line 75, in set
>     'config values may not be unicode strings on Python 3')
> AssertionError: b'config values may not be unicode strings on Python 3'

**Comment by nobody93** [comment] 2018-07-18 04:17
Hi, 

I thought I wrote following comments yesterday, but could not see it. Sorry I have to write it again, I've clone it from the master branch but I still have following errors, does it requires to run python3? The command PYTHON=${PYTHON:-python} is for python 2. Anyway, is it fixed in any branch?

File "/storage/data/SolarAnalytics/HAN/fast-export/hg-fast-export.py", line 7, in <module>
    from mercurial.scmutil import revsymbol
ImportError: cannot import name revsymbol

**Comment by frej** [comment] 2018-07-20 15:13
@nobody93: Looks like a duplicate of #132.

**Comment by frej** [comment] 2018-08-11 13:25
@jeandersonbc: As long as Mercurial [does not fully support](https://www.mercurial-scm.org/wiki/SupportedPythonVersions) Python >= 3 porting fast-export to Python 3 is pretty pointless.

Commit ac60034 should make it clear that Python 3 is not supported even if the requirements section in the readme is ignored. With [PEP 394](https://www.python.org/dev/peps/pep-0394/)  now providing guidance on what a Python script should assume, I believe this bug is finally fixed.

**Closed by frej** 2018-08-11 13:25 UTC
