### ISSUE TITLE
Importing mercurial repository fails with syntax error

### ISSUE THREAD

**Issue by LinuxUserGD** [frej/fast-export#323] opened 2024-02-24 13:01 UTC
OS: Gentoo Linux (amd64 musl libc)
Python version: 3.11.8
[hg-fast-export-231118.ebuild](https://github.com/stefantalpalaru/gentoo-overlay/blob/master/dev-vcs/hg-fast-export/hg-fast-export-231118.ebuild)

Steps to reproduce:
```bash
hg clone https://hg.mozilla.org/mozilla-central/ firefox
mkdir firefox
git init
cd firefox
hg-fast-export -r firefox
```
```bash
master: Exporting simple delta revision 28463/696784 with 2/0 modified/removed files
fatal: Missing > in ident string: Gregory Maxwell <<gmaxwell@gmail.com> 1242598744 +1200
fast-import: dumping crash report to .git/fast_import_crash_4384
master: Exporting simple delta revision 28464/696784 with 9/0 modified/removed files
master: Exporting simple delta revision 28465/696784 with 2/0 modified/removed files
master: Exporting simple delta revision 28466/696784 with 3/1 modified/removed files
master: Exporting simple delta revision 28467/696784 with 3/0 modified/removed files
master: Exporting simple delta revision 28468/696784 with 5/0 modified/removed files
master: Exporting simple delta revision 28469/696784 with 2/0 modified/removed files
master: Exporting simple delta revision 28470/696784 with 1/0 modified/removed files
master: Exporting simple delta revision 28471/696784 with 3/0 modified/removed files
master: Exporting simple delta revision 28472/696784 with 10/0 modified/removed files
master: Exporting simple delta revision 28473/696784 with 5/0 modified/removed files
master: Exporting simple delta revision 28474/696784 with 2/0 modified/removed files
Traceback (most recent call last):
  File "/usr/bin/hg-fast-export.py", line 98, in <module>
    exec(data, new_globals)
  File "<string>", line 698, in <module>
  File "<string>", line 551, in hg2git
  File "<string>", line 336, in export_commit
  File "<string>", line 214, in export_file_contents
  File "<string>", line 52, in wr
  File "<string>", line 49, in wr_no_nl
BrokenPipeError: [Errno 32] Broken pipe
```
```bash
fast-import crash report:
    fast-import process: 4384
    parent process     : 4383
    at 2024-02-24 12:45:24 +0000

fatal: Missing > in ident string: Gregory Maxwell <<gmaxwell@gmail.com> 1242598744 +1200

Most Recent Commands Before Crash
---------------------------------
  commit refs/heads/master
  mark :28466
  committer Boris Zbarsky <bzbarsky@mit.edu> 1242580340 -0400
  data 11
  from :28465
  D content/base/test/test_bug490760.xhtml
  M 100644 inline content/base/crashtests/crashtests.list
  data 1000
  M 100644 inline content/base/test/Makefile.in
  data 9249
  M 100644 inline content/base/crashtests/490760-1.xhtml
  data 540
  
  commit refs/heads/master
  mark :28467
  committer Daniel.S <crazy-daniel@gmx.de> 1242589910 -0400
  data 38
  from :28466
  M 100644 inline layout/reftests/bugs/reftest.list
  data 49133
  M 100644 inline layout/reftests/bugs/329359-1-ref.html
  data 507
  M 100644 inline layout/reftests/bugs/329359-1.html
  data 538
  
  commit refs/heads/master
  mark :28468
  committer Asaf Romano <aromano@mozilla.com> 1242591267 +0300
  data 67
  from :28467
  M 100644 inline browser/base/content/browser-places.js
  data 36689
  M 100644 inline browser/components/places/content/bookmarkProperties.js
  data 24026
  M 100644 inline browser/components/places/src/nsPlacesTransactionsService.js
  data 39440
  M 100644 inline browser/components/places/tests/unit/test_placesTxn.js
  data 33912
  M 100644 inline build/wince/tools/Makefile
  data 2018
  
  commit refs/heads/master
  mark :28469
  committer Robert O'Callahan <robert@ocallahan.org> 1242597783 +1200
  data 78
  from :28468
  M 100644 inline content/media/video/src/nsOggDecoder.cpp
  data 72901
  M 100644 inline content/media/video/test/test_bug476973.html
  data 1678
  
  commit refs/heads/master
  mark :28470
  committer Robert O'Callahan <robert@ocallahan.org> 1242598088 +1200
  data 69
  from :28469
  M 100644 inline content/base/src/nsContentUtils.cpp
  data 146400
  
  commit refs/heads/master
  mark :28471
  committer Robert O'Callahan <robert@ocallahan.org> 1242598193 +1200
  data 96
  from :28470
  M 100644 inline gfx/src/thebes/nsThebesDeviceContext.cpp
  data 39125
  M 100644 inline layout/base/nsPresContext.cpp
  data 68985
  M 100644 inline modules/libpref/src/init/all.js
  data 114235
  
  commit refs/heads/master
  mark :28472
  committer Chris Pearce <chris@pearce.org.nz> 1242598557 +1200
  data 176
  from :28471
  M 100644 inline content/media/video/public/nsMediaCache.h
  data 21885
  M 100644 inline content/media/video/public/nsMediaStream.h
  data 15696
  M 100644 inline content/media/video/src/nsChannelReader.cpp
  data 7581
  M 100644 inline content/media/video/src/nsMediaCache.cpp
  data 65952
  M 100644 inline content/media/video/src/nsMediaStream.cpp
  data 28321
  M 100644 inline media/liboggz/README_MOZILLA
  data 547
  M 100644 inline media/liboggz/include/oggz/oggz_seek.h
  data 20141
  M 100644 inline media/liboggz/src/liboggz/oggz_seek.c
  data 22645
  M 100644 inline media/liboggz/update.sh
  data 4365
  M 100644 inline media/liboggz/bounded_seek.patch
  data 10028
  
  commit refs/heads/master
  mark :28473
* committer Gregory Maxwell <<gmaxwell@gmail.com> 1242598744 +1200

Active Branch LRU
-----------------
    active_branches = 4 cur, 5 max

  pos  clock name
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1)  25667 refs/heads/GECKO191b2_20081125_RELBRANCH
   2)  20483 refs/heads/FENNEC_A1_BRANCH
   3)  20103 refs/heads/GECKO191b1_20081007_RELBRANCH
   4)  28472 refs/heads/master

Inactive Branches
-----------------
refs/heads/GECKO191b1_20081007_RELBRANCH:
  status      : active loaded
  tip commit  : de8acca9c52f294215a1ea83e71290da64f2227d
  old tree    : 6979582dab1e306b936956f75219bb81df36d3b2
  cur tree    : 6979582dab1e306b936956f75219bb81df36d3b2
  commit clock: 20103
  last pack   : 0

refs/heads/scalable_gc_free_lists_378918:
  status      :
  tip commit  : 788e89ffc1159c438caec228882d04dd4fadf719
  old tree    : 859b8d269103d6a48c291f6dde845d448c244a21
  cur tree    : 859b8d269103d6a48c291f6dde845d448c244a21
  commit clock: 15493
  last pack   : 0

refs/heads/GECKO191b2_20081125_RELBRANCH:
  status      : active loaded
  tip commit  : 325c5551fdb2c3a27fa8c2d496c9cb9d33db13f0
  old tree    : 546f8f87d2fc4d07276e02874125a0eb2a97ede2
  cur tree    : 546f8f87d2fc4d07276e02874125a0eb2a97ede2
  commit clock: 25667
  last pack   : 0

refs/heads/FENNEC_A1_BRANCH:
  status      : active loaded
  tip commit  : 65b4ea62e9674fe5892167a25b258a5a1a49a411
  old tree    : 6de302a21bb16e223287de1f4f37b6ae34a23ba8
  cur tree    : 6de302a21bb16e223287de1f4f37b6ae34a23ba8
  commit clock: 20483
  last pack   : 0

refs/heads/master:
  status      : active loaded
  tip commit  : ff0ab481553bf5952e979d8da52a8f5927bd078d
  old tree    : 0311d23cfe05200c085976d91439d24f784b7042
  cur tree    : 0311d23cfe05200c085976d91439d24f784b7042
  commit clock: 28472
  last pack   : 0


Marks
-----
  exported to .git/hg2git-marks.tmp

-------------------
END OF CRASH REPORT
```

**Comment by frej** [comment] 2024-02-24 16:29
Duplicate of #43, check the  [frequent problems section](https://github.com/frej/fast-export?tab=readme-ov-file#frequent-problems) of the readme for gotchas when using author maps.

**Closed by frej** 2024-02-24 16:29 UTC
Labels: not-a-bug
